Version: 0.2
Phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip3 install --upgrade pip
      - pip3 install requests[security]
      - pip3 install ansible
      - pip3 install boto
      - pip3 install boto3
      - yum clean all
      - yum -y install curl
      - yum -y install jq
  build:
    commands:
      - cd ansible
      - chmod +x botos3.py
      - python botos3.py
      #- s3 = boto3.client("s3")
      #- s3.create_bucket(Bucket='mybucket')
      #- echo "completed"
      #- cd ansible
      #- ansible-playbook create_s3.yml
      #- export ORG="twe"
      #- cd ansible
      #- chmod +x inventory/aws_accounts.py
      #- ansible-playbook 02-deploy-common-prerequisites.yml
      
