---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: myansiblebucket
      #policy: "{{ lookup( 'file','my_bucket_policy.json' )}}"
      state: present
      region: ap-southeast-1
      versioning: no
      tags:
         name: myansiblebucket
         type: example
