---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: myansiblebucket
      aws_access_key: xxxxxxx
      aws_secret_key: xxxxxxx
      policy: "{{ lookup( 'file','my_bucket_policy.json' )}}"
      state: present
      region: xxxxxx
      versioning: no
      tags:
         name: myansiblebucket
         type: example